# Generated by Django 4.2 on 2023-05-29 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratingsANDreviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='receiver',
            new_name='receiverId',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='receiver',
            new_name='receiverId',
        ),
    ]
